package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *aiExportResolver) CreatedAt(ctx context.Context, obj *models.AiExport) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.CreatedAt)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *aiExportResolver) UpdatedAt(ctx context.Context, obj *models.AiExport) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.UpdatedAt)
}

// ValidationError is the resolver for the validationError field.
func (r *aiExportResultResolver) ValidationError(ctx context.Context, obj *models.AiExportResult) (*models.AiExportValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *aiExportResultResolver) NotFoundError(ctx context.Context, obj *models.AiExportResult) (*models.AiExportNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *aiExportResultResolver) AuthError(ctx context.Context, obj *models.AiExportResult) (*models.AiExportAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *aiExportsResultResolver) ValidationError(ctx context.Context, obj *models.AiExportsResult) (*models.AiExportValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *aiExportsResultResolver) AuthError(ctx context.Context, obj *models.AiExportsResult) (*models.AiExportAuthErr, error) {
	return obj.AuthErr, nil
}

// AiExport returns generated.AiExportResolver implementation.
func (r *Resolver) AiExport() generated.AiExportResolver { return &aiExportResolver{r} }

// AiExportResult returns generated.AiExportResultResolver implementation.
func (r *Resolver) AiExportResult() generated.AiExportResultResolver {
	return &aiExportResultResolver{r}
}

// AiExportsResult returns generated.AiExportsResultResolver implementation.
func (r *Resolver) AiExportsResult() generated.AiExportsResultResolver {
	return &aiExportsResultResolver{r}
}

type aiExportResolver struct{ *Resolver }
type aiExportResultResolver struct{ *Resolver }
type aiExportsResultResolver struct{ *Resolver }
