package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *aiReviewResolver) CreatedAt(ctx context.Context, obj *models.AiReview) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.CreatedAt)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *aiReviewResolver) UpdatedAt(ctx context.Context, obj *models.AiReview) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.UpdatedAt)
}

// ValidationError is the resolver for the validationError field.
func (r *aiReviewResultResolver) ValidationError(ctx context.Context, obj *models.AiReviewResult) (*models.AiReviewValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *aiReviewResultResolver) NotFoundError(ctx context.Context, obj *models.AiReviewResult) (*models.AiReviewNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *aiReviewResultResolver) AuthError(ctx context.Context, obj *models.AiReviewResult) (*models.AiReviewAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *aiReviewsResultResolver) ValidationError(ctx context.Context, obj *models.AiReviewsResult) (*models.AiReviewValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *aiReviewsResultResolver) AuthError(ctx context.Context, obj *models.AiReviewsResult) (*models.AiReviewAuthErr, error) {
	return obj.AuthErr, nil
}

// AiReview returns generated.AiReviewResolver implementation.
func (r *Resolver) AiReview() generated.AiReviewResolver { return &aiReviewResolver{r} }

// AiReviewResult returns generated.AiReviewResultResolver implementation.
func (r *Resolver) AiReviewResult() generated.AiReviewResultResolver {
	return &aiReviewResultResolver{r}
}

// AiReviewsResult returns generated.AiReviewsResultResolver implementation.
func (r *Resolver) AiReviewsResult() generated.AiReviewsResultResolver {
	return &aiReviewsResultResolver{r}
}

type aiReviewResolver struct{ *Resolver }
type aiReviewResultResolver struct{ *Resolver }
type aiReviewsResultResolver struct{ *Resolver }
