package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *bodyCheckInResolver) CreatedAt(ctx context.Context, obj *models.BodyCheckIn) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *bodyCheckInResolver) UpdatedAt(ctx context.Context, obj *models.BodyCheckIn) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *bodyCheckInResultResolver) ValidationError(ctx context.Context, obj *models.BodyCheckInResult) (*models.BodyValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *bodyCheckInResultResolver) NotFoundError(ctx context.Context, obj *models.BodyCheckInResult) (*models.BodyNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *bodyCheckInResultResolver) AuthError(ctx context.Context, obj *models.BodyCheckInResult) (*models.BodyAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *bodyCheckInsResultResolver) ValidationError(ctx context.Context, obj *models.BodyCheckInsResult) (*models.BodyValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *bodyCheckInsResultResolver) AuthError(ctx context.Context, obj *models.BodyCheckInsResult) (*models.BodyAuthErr, error) {
	return obj.AuthErr, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *bodyMeasurementResolver) CreatedAt(ctx context.Context, obj *models.BodyMeasurement) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *bodyMeasurementResolver) UpdatedAt(ctx context.Context, obj *models.BodyMeasurement) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *bodyMeasurementResultResolver) ValidationError(ctx context.Context, obj *models.BodyMeasurementResult) (*models.BodyValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *bodyMeasurementResultResolver) NotFoundError(ctx context.Context, obj *models.BodyMeasurementResult) (*models.BodyNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *bodyMeasurementResultResolver) AuthError(ctx context.Context, obj *models.BodyMeasurementResult) (*models.BodyAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *bodyWeightEntriesResultResolver) ValidationError(ctx context.Context, obj *models.BodyWeightEntriesResult) (*models.BodyValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *bodyWeightEntriesResultResolver) AuthError(ctx context.Context, obj *models.BodyWeightEntriesResult) (*models.BodyAuthErr, error) {
	return obj.AuthErr, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *bodyWeightEntryResolver) CreatedAt(ctx context.Context, obj *models.BodyWeightEntry) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *bodyWeightEntryResolver) UpdatedAt(ctx context.Context, obj *models.BodyWeightEntry) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *bodyWeightResultResolver) ValidationError(ctx context.Context, obj *models.BodyWeightResult) (*models.BodyValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *bodyWeightResultResolver) NotFoundError(ctx context.Context, obj *models.BodyWeightResult) (*models.BodyNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *bodyWeightResultResolver) AuthError(ctx context.Context, obj *models.BodyWeightResult) (*models.BodyAuthErr, error) {
	return obj.AuthErr, nil
}

// BodyCheckIn returns generated.BodyCheckInResolver implementation.
func (r *Resolver) BodyCheckIn() generated.BodyCheckInResolver { return &bodyCheckInResolver{r} }

// BodyCheckInResult returns generated.BodyCheckInResultResolver implementation.
func (r *Resolver) BodyCheckInResult() generated.BodyCheckInResultResolver {
	return &bodyCheckInResultResolver{r}
}

// BodyCheckInsResult returns generated.BodyCheckInsResultResolver implementation.
func (r *Resolver) BodyCheckInsResult() generated.BodyCheckInsResultResolver {
	return &bodyCheckInsResultResolver{r}
}

// BodyMeasurement returns generated.BodyMeasurementResolver implementation.
func (r *Resolver) BodyMeasurement() generated.BodyMeasurementResolver {
	return &bodyMeasurementResolver{r}
}

// BodyMeasurementResult returns generated.BodyMeasurementResultResolver implementation.
func (r *Resolver) BodyMeasurementResult() generated.BodyMeasurementResultResolver {
	return &bodyMeasurementResultResolver{r}
}

// BodyWeightEntriesResult returns generated.BodyWeightEntriesResultResolver implementation.
func (r *Resolver) BodyWeightEntriesResult() generated.BodyWeightEntriesResultResolver {
	return &bodyWeightEntriesResultResolver{r}
}

// BodyWeightEntry returns generated.BodyWeightEntryResolver implementation.
func (r *Resolver) BodyWeightEntry() generated.BodyWeightEntryResolver {
	return &bodyWeightEntryResolver{r}
}

// BodyWeightResult returns generated.BodyWeightResultResolver implementation.
func (r *Resolver) BodyWeightResult() generated.BodyWeightResultResolver {
	return &bodyWeightResultResolver{r}
}

type bodyCheckInResolver struct{ *Resolver }
type bodyCheckInResultResolver struct{ *Resolver }
type bodyCheckInsResultResolver struct{ *Resolver }
type bodyMeasurementResolver struct{ *Resolver }
type bodyMeasurementResultResolver struct{ *Resolver }
type bodyWeightEntriesResultResolver struct{ *Resolver }
type bodyWeightEntryResolver struct{ *Resolver }
type bodyWeightResultResolver struct{ *Resolver }
