package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// ValidationError is the resolver for the validationError field.
func (r *cardioEntriesResultResolver) ValidationError(ctx context.Context, obj *models.CardioEntriesResult) (*models.CardioValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *cardioEntriesResultResolver) AuthError(ctx context.Context, obj *models.CardioEntriesResult) (*models.CardioAuthErr, error) {
	return obj.AuthErr, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *cardioEntryResolver) CreatedAt(ctx context.Context, obj *models.CardioEntry) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *cardioEntryResolver) UpdatedAt(ctx context.Context, obj *models.CardioEntry) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *cardioEntryResultResolver) ValidationError(ctx context.Context, obj *models.CardioEntryResult) (*models.CardioValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *cardioEntryResultResolver) NotFoundError(ctx context.Context, obj *models.CardioEntryResult) (*models.CardioNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *cardioEntryResultResolver) AuthError(ctx context.Context, obj *models.CardioEntryResult) (*models.CardioAuthErr, error) {
	return obj.AuthErr, nil
}

// CardioEntriesResult returns generated.CardioEntriesResultResolver implementation.
func (r *Resolver) CardioEntriesResult() generated.CardioEntriesResultResolver {
	return &cardioEntriesResultResolver{r}
}

// CardioEntry returns generated.CardioEntryResolver implementation.
func (r *Resolver) CardioEntry() generated.CardioEntryResolver { return &cardioEntryResolver{r} }

// CardioEntryResult returns generated.CardioEntryResultResolver implementation.
func (r *Resolver) CardioEntryResult() generated.CardioEntryResultResolver {
	return &cardioEntryResultResolver{r}
}

type cardioEntriesResultResolver struct{ *Resolver }
type cardioEntryResolver struct{ *Resolver }
type cardioEntryResultResolver struct{ *Resolver }
