package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
)

// ValidationError is the resolver for the validationError field.
func (r *bodyWeightTrendResultResolver) ValidationError(ctx context.Context, obj *models.BodyWeightTrendResult) (*models.ChartValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *bodyWeightTrendResultResolver) AuthError(ctx context.Context, obj *models.BodyWeightTrendResult) (*models.ChartAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *exerciseProgressResultResolver) ValidationError(ctx context.Context, obj *models.ExerciseProgressResult) (*models.ChartValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *exerciseProgressResultResolver) AuthError(ctx context.Context, obj *models.ExerciseProgressResult) (*models.ChartAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *measurementOverlayResultResolver) ValidationError(ctx context.Context, obj *models.MeasurementOverlayResult) (*models.ChartValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *measurementOverlayResultResolver) AuthError(ctx context.Context, obj *models.MeasurementOverlayResult) (*models.ChartAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *measurementTrendResultResolver) ValidationError(ctx context.Context, obj *models.MeasurementTrendResult) (*models.ChartValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *measurementTrendResultResolver) AuthError(ctx context.Context, obj *models.MeasurementTrendResult) (*models.ChartAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *nutritionWeeklyAveragesResultResolver) ValidationError(ctx context.Context, obj *models.NutritionWeeklyAveragesResult) (*models.ChartValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *nutritionWeeklyAveragesResultResolver) AuthError(ctx context.Context, obj *models.NutritionWeeklyAveragesResult) (*models.ChartAuthErr, error) {
	return obj.AuthErr, nil
}

// BodyWeightTrendResult returns generated.BodyWeightTrendResultResolver implementation.
func (r *Resolver) BodyWeightTrendResult() generated.BodyWeightTrendResultResolver {
	return &bodyWeightTrendResultResolver{r}
}

// ExerciseProgressResult returns generated.ExerciseProgressResultResolver implementation.
func (r *Resolver) ExerciseProgressResult() generated.ExerciseProgressResultResolver {
	return &exerciseProgressResultResolver{r}
}

// MeasurementOverlayResult returns generated.MeasurementOverlayResultResolver implementation.
func (r *Resolver) MeasurementOverlayResult() generated.MeasurementOverlayResultResolver {
	return &measurementOverlayResultResolver{r}
}

// MeasurementTrendResult returns generated.MeasurementTrendResultResolver implementation.
func (r *Resolver) MeasurementTrendResult() generated.MeasurementTrendResultResolver {
	return &measurementTrendResultResolver{r}
}

// NutritionWeeklyAveragesResult returns generated.NutritionWeeklyAveragesResultResolver implementation.
func (r *Resolver) NutritionWeeklyAveragesResult() generated.NutritionWeeklyAveragesResultResolver {
	return &nutritionWeeklyAveragesResultResolver{r}
}

type bodyWeightTrendResultResolver struct{ *Resolver }
type exerciseProgressResultResolver struct{ *Resolver }
type measurementOverlayResultResolver struct{ *Resolver }
type measurementTrendResultResolver struct{ *Resolver }
type nutritionWeeklyAveragesResultResolver struct{ *Resolver }
