package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *dailyNutritionEntryResolver) CreatedAt(ctx context.Context, obj *models.DailyNutritionEntry) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.CreatedAt)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *dailyNutritionEntryResolver) UpdatedAt(ctx context.Context, obj *models.DailyNutritionEntry) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.UpdatedAt)
}

// Date is the resolver for the date field.
func (r *dailyNutritionLogResolver) Date(ctx context.Context, obj *models.DailyNutritionLog) (*models.Date, error) {
	return atlasGraphQLDatePtr(obj.Date)
}

// CreatedAt is the resolver for the createdAt field.
func (r *dailyNutritionLogResolver) CreatedAt(ctx context.Context, obj *models.DailyNutritionLog) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.CreatedAt)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *dailyNutritionLogResolver) UpdatedAt(ctx context.Context, obj *models.DailyNutritionLog) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.UpdatedAt)
}

// ValidationError is the resolver for the validationError field.
func (r *dailyNutritionLogResultResolver) ValidationError(ctx context.Context, obj *models.DailyNutritionLogResult) (*models.NutritionValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *dailyNutritionLogResultResolver) NotFoundError(ctx context.Context, obj *models.DailyNutritionLogResult) (*models.NutritionNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *dailyNutritionLogResultResolver) AuthError(ctx context.Context, obj *models.DailyNutritionLogResult) (*models.NutritionAuthErr, error) {
	return obj.AuthErr, nil
}

// DailyNutritionEntry returns generated.DailyNutritionEntryResolver implementation.
func (r *Resolver) DailyNutritionEntry() generated.DailyNutritionEntryResolver {
	return &dailyNutritionEntryResolver{r}
}

// DailyNutritionLog returns generated.DailyNutritionLogResolver implementation.
func (r *Resolver) DailyNutritionLog() generated.DailyNutritionLogResolver {
	return &dailyNutritionLogResolver{r}
}

// DailyNutritionLogResult returns generated.DailyNutritionLogResultResolver implementation.
func (r *Resolver) DailyNutritionLogResult() generated.DailyNutritionLogResultResolver {
	return &dailyNutritionLogResultResolver{r}
}

type dailyNutritionEntryResolver struct{ *Resolver }
type dailyNutritionLogResolver struct{ *Resolver }
type dailyNutritionLogResultResolver struct{ *Resolver }
