// FILE: apps/api/internal/atlas/graph/resolver/exercise.go
// VERSION: 1.0.0
// START_MODULE_CONTRACT
//   PURPOSE: Implement GraphQL resolvers for WAVE-02 Exercise Library queries and mutations.
//   SCOPE: exercise(id), exercises(pagination), allExercises, createExercise, updateExercise, archiveExercise, restoreExercise. Field resolvers live in generated exercises.resolvers.go.
//   DEPENDS: apps/api/internal/atlas/service.ExerciseService, apps/api/internal/atlas/middleware, apps/api/internal/atlas/models, generated exercises.resolvers.go.
//   LINKS: M-API / V-M-API / WAVE-02.
//   ROLE: RUNTIME
//   MAP_MODE: EXPORTS
// END_MODULE_CONTRACT
// START_CHANGE_SUMMARY
//   LAST_CHANGE: 1.0.1 - Removed duplicate queryResolver/mutationResolver and field resolver methods now generated by gqlgen in schema.resolvers.go / exercises.resolvers.go.
// END_CHANGE_SUMMARY

package resolver

import (
	"context"
	"errors"

	"monorepo-template/apps/api/internal/atlas/middleware"
	"monorepo-template/apps/api/internal/atlas/models"
	atlasService "monorepo-template/apps/api/internal/atlas/service"
)

func (r *Resolver) Exercises(ctx context.Context, first *int, after *string, includeInactive *bool) (*models.ExerciseConnection, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return nil, nil
	}

	f := int32(20)
	if first != nil && *first > 0 {
		f = int32(*first)
	}
	ii := false
	if includeInactive != nil {
		ii = *includeInactive
	}

	conn, err := r.ExerciseService.List(ctx, userID, f, after, ii)
	if err != nil {
		return nil, nil
	}

	return conn, nil
}

func (r *Resolver) GetExercise(ctx context.Context, id string) (*models.ExerciseResult, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return &models.ExerciseResult{
			AuthErr: &models.AuthErr{
				Message: "unauthorized",
				Code:    models.ExerciseErrorAuth,
			},
		}, nil
	}

	exercise, err := r.ExerciseService.GetByID(ctx, userID, id)
	if err != nil {
		if errors.Is(err, atlasService.ErrExerciseNotFound) {
			return &models.ExerciseResult{
				NotFoundErr: &models.NotFoundErr{
					Message: "exercise not found",
					Code:    models.ExerciseErrorNotFound,
				},
			}, nil
		}
		return nil, nil
	}

	return &models.ExerciseResult{Exercise: exercise}, nil
}

func (r *Resolver) AllExercises(ctx context.Context, includeInactive *bool) ([]*models.Exercise, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return nil, nil
	}

	ii := false
	if includeInactive != nil {
		ii = *includeInactive
	}

	exercises, err := r.ExerciseService.ListAll(ctx, userID, ii)
	if err != nil {
		return nil, nil
	}

	items := make([]*models.Exercise, len(exercises))
	for i := range exercises {
		items[i] = &exercises[i]
	}
	return items, nil
}

func (r *Resolver) CreateExercise(ctx context.Context, input models.CreateExerciseInput) (*models.ExerciseResult, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return &models.ExerciseResult{
			AuthErr: &models.AuthErr{
				Message: "unauthorized",
				Code:    models.ExerciseErrorAuth,
			},
		}, nil
	}

	exercise, err := r.ExerciseService.Create(ctx, userID, input)
	if err != nil {
		switch {
		case errors.Is(err, atlasService.ErrExerciseNameEmpty), errors.Is(err, atlasService.ErrWeightInvalid):
			return &models.ExerciseResult{
				ValidationErr: &models.ValidationErr{
					Message: err.Error(),
					Code:    models.ExerciseErrorValidation,
				},
			}, nil
		default:
			return nil, nil
		}
	}

	return &models.ExerciseResult{Exercise: exercise}, nil
}

func (r *Resolver) UpdateExercise(ctx context.Context, id string, input models.UpdateExerciseInput) (*models.ExerciseResult, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return &models.ExerciseResult{
			AuthErr: &models.AuthErr{
				Message: "unauthorized",
				Code:    models.ExerciseErrorAuth,
			},
		}, nil
	}

	exercise, err := r.ExerciseService.Update(ctx, userID, id, input)
	if err != nil {
		switch {
		case errors.Is(err, atlasService.ErrExerciseNameEmpty), errors.Is(err, atlasService.ErrWeightInvalid):
			return &models.ExerciseResult{
				ValidationErr: &models.ValidationErr{
					Message: err.Error(),
					Code:    models.ExerciseErrorValidation,
				},
			}, nil
		case errors.Is(err, atlasService.ErrExerciseNotFound):
			return &models.ExerciseResult{
				NotFoundErr: &models.NotFoundErr{
					Message: "exercise not found",
					Code:    models.ExerciseErrorNotFound,
				},
			}, nil
		default:
			return nil, nil
		}
	}

	return &models.ExerciseResult{Exercise: exercise}, nil
}

func (r *Resolver) ArchiveExercise(ctx context.Context, id string) (*models.ArchiveResult, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return &models.ArchiveResult{
			AuthErr: &models.AuthErr{
				Message: "unauthorized",
				Code:    models.ExerciseErrorAuth,
			},
		}, nil
	}

	exercise, err := r.ExerciseService.Archive(ctx, userID, id)
	if err != nil {
		if errors.Is(err, atlasService.ErrExerciseNotFound) {
			return &models.ArchiveResult{
				NotFoundErr: &models.NotFoundErr{
					Message: "exercise not found",
					Code:    models.ExerciseErrorNotFound,
				},
			}, nil
		}
		return nil, nil
	}

	return &models.ArchiveResult{Exercise: exercise}, nil
}

func (r *Resolver) RestoreExercise(ctx context.Context, id string) (*models.ArchiveResult, error) {
	userID := middleware.GetAtlasUserID(ctx)
	if userID == "" {
		return &models.ArchiveResult{
			AuthErr: &models.AuthErr{
				Message: "unauthorized",
				Code:    models.ExerciseErrorAuth,
			},
		}, nil
	}

	exercise, err := r.ExerciseService.Restore(ctx, userID, id)
	if err != nil {
		if errors.Is(err, atlasService.ErrExerciseNotFound) {
			return &models.ArchiveResult{
				NotFoundErr: &models.NotFoundErr{
					Message: "exercise not found",
					Code:    models.ExerciseErrorNotFound,
				},
			}, nil
		}
		return nil, nil
	}

	return &models.ArchiveResult{Exercise: exercise}, nil
}