package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// NotFoundError is the resolver for the notFoundError field.
func (r *archiveResultResolver) NotFoundError(ctx context.Context, obj *models.ArchiveResult) (*models.NotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *archiveResultResolver) AuthError(ctx context.Context, obj *models.ArchiveResult) (*models.AuthErr, error) {
	return obj.AuthErr, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *exerciseResolver) CreatedAt(ctx context.Context, obj *models.Exercise) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *exerciseResolver) UpdatedAt(ctx context.Context, obj *models.Exercise) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *exerciseMediaResolver) CreatedAt(ctx context.Context, obj *models.ExerciseMedia) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *exerciseResultResolver) ValidationError(ctx context.Context, obj *models.ExerciseResult) (*models.ValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *exerciseResultResolver) NotFoundError(ctx context.Context, obj *models.ExerciseResult) (*models.NotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *exerciseResultResolver) AuthError(ctx context.Context, obj *models.ExerciseResult) (*models.AuthErr, error) {
	return obj.AuthErr, nil
}

// ArchiveResult returns generated.ArchiveResultResolver implementation.
func (r *Resolver) ArchiveResult() generated.ArchiveResultResolver { return &archiveResultResolver{r} }

// Exercise returns generated.ExerciseResolver implementation.
func (r *Resolver) Exercise() generated.ExerciseResolver { return &exerciseResolver{r} }

// ExerciseMedia returns generated.ExerciseMediaResolver implementation.
func (r *Resolver) ExerciseMedia() generated.ExerciseMediaResolver { return &exerciseMediaResolver{r} }

// ExerciseResult returns generated.ExerciseResultResolver implementation.
func (r *Resolver) ExerciseResult() generated.ExerciseResultResolver {
	return &exerciseResultResolver{r}
}

type archiveResultResolver struct{ *Resolver }
type exerciseResolver struct{ *Resolver }
type exerciseMediaResolver struct{ *Resolver }
type exerciseResultResolver struct{ *Resolver }
