package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *progressPhotoResolver) CreatedAt(ctx context.Context, obj *models.ProgressPhoto) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *progressPhotoResolver) UpdatedAt(ctx context.Context, obj *models.ProgressPhoto) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *progressPhotosResultResolver) ValidationError(ctx context.Context, obj *models.ProgressPhotosResult) (*models.ProgressPhotoValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *progressPhotosResultResolver) AuthError(ctx context.Context, obj *models.ProgressPhotosResult) (*models.ProgressPhotoAuthErr, error) {
	return obj.AuthErr, nil
}

// ProgressPhoto returns generated.ProgressPhotoResolver implementation.
func (r *Resolver) ProgressPhoto() generated.ProgressPhotoResolver { return &progressPhotoResolver{r} }

// ProgressPhotosResult returns generated.ProgressPhotosResultResolver implementation.
func (r *Resolver) ProgressPhotosResult() generated.ProgressPhotosResultResolver {
	return &progressPhotosResultResolver{r}
}

type progressPhotoResolver struct{ *Resolver }
type progressPhotosResultResolver struct{ *Resolver }
