package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input models.SettingsInput) (*models.SettingsResult, error) {
	panic(fmt.Errorf("not implemented: UpdateSettings - updateSettings"))
}

// EnablePin is the resolver for the enablePin field.
func (r *mutationResolver) EnablePin(ctx context.Context, input models.PinEnableInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: EnablePin - enablePin"))
}

// DisablePin is the resolver for the disablePin field.
func (r *mutationResolver) DisablePin(ctx context.Context, input models.PinDisableInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: DisablePin - disablePin"))
}

// ChangePin is the resolver for the changePin field.
func (r *mutationResolver) ChangePin(ctx context.Context, input models.PinChangeInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: ChangePin - changePin"))
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*models.SettingsResult, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
