package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input models.SettingsInput) (*models.SettingsResult, error) {
	panic(fmt.Errorf("not implemented: UpdateSettings - updateSettings"))
}

// EnablePin is the resolver for the enablePin field.
func (r *mutationResolver) EnablePin(ctx context.Context, input models.PinEnableInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: EnablePin - enablePin"))
}

// DisablePin is the resolver for the disablePin field.
func (r *mutationResolver) DisablePin(ctx context.Context, input models.PinDisableInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: DisablePin - disablePin"))
}

// ChangePin is the resolver for the changePin field.
func (r *mutationResolver) ChangePin(ctx context.Context, input models.PinChangeInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: ChangePin - changePin"))
}

// CreateExercise is the resolver for the createExercise field.
func (r *mutationResolver) CreateExercise(ctx context.Context, input models.CreateExerciseInput) (*models.ExerciseResult, error) {
	return r.Resolver.CreateExercise(ctx, input)
}

// UpdateExercise is the resolver for the updateExercise field.
func (r *mutationResolver) UpdateExercise(ctx context.Context, id string, input models.UpdateExerciseInput) (*models.ExerciseResult, error) {
	return r.Resolver.UpdateExercise(ctx, id, input)
}

// ArchiveExercise is the resolver for the archiveExercise field.
func (r *mutationResolver) ArchiveExercise(ctx context.Context, id string) (*models.ArchiveResult, error) {
	return r.Resolver.ArchiveExercise(ctx, id)
}

// RestoreExercise is the resolver for the restoreExercise field.
func (r *mutationResolver) RestoreExercise(ctx context.Context, id string) (*models.ArchiveResult, error) {
	return r.Resolver.RestoreExercise(ctx, id)
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*models.SettingsResult, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Exercises is the resolver for the exercises field.
func (r *queryResolver) Exercises(ctx context.Context, first *int, after *string, includeInactive *bool) (*models.ExerciseConnection, error) {
	return r.Resolver.Exercises(ctx, first, after, includeInactive)
}

// Exercise is the resolver for the exercise field.
func (r *queryResolver) Exercise(ctx context.Context, id string) (*models.ExerciseResult, error) {
	return r.Resolver.GetExercise(ctx, id)
}

// AllExercises is the resolver for the allExercises field.
func (r *queryResolver) AllExercises(ctx context.Context, includeInactive *bool) ([]*models.Exercise, error) {
	return r.Resolver.AllExercises(ctx, includeInactive)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
