package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input models.SettingsInput) (*models.SettingsResult, error) {
	panic(fmt.Errorf("not implemented: UpdateSettings - updateSettings"))
}

// EnablePin is the resolver for the enablePin field.
func (r *mutationResolver) EnablePin(ctx context.Context, input models.PinEnableInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: EnablePin - enablePin"))
}

// DisablePin is the resolver for the disablePin field.
func (r *mutationResolver) DisablePin(ctx context.Context, input models.PinDisableInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: DisablePin - disablePin"))
}

// ChangePin is the resolver for the changePin field.
func (r *mutationResolver) ChangePin(ctx context.Context, input models.PinChangeInput) (*models.PinOperationResult, error) {
	panic(fmt.Errorf("not implemented: ChangePin - changePin"))
}

// CreateExercise is the resolver for the createExercise field.
func (r *mutationResolver) CreateExercise(ctx context.Context, input models.CreateExerciseInput) (*models.ExerciseResult, error) {
	return r.Resolver.CreateExercise(ctx, input)
}

// UpdateExercise is the resolver for the updateExercise field.
func (r *mutationResolver) UpdateExercise(ctx context.Context, id string, input models.UpdateExerciseInput) (*models.ExerciseResult, error) {
	return r.Resolver.UpdateExercise(ctx, id, input)
}

// ArchiveExercise is the resolver for the archiveExercise field.
func (r *mutationResolver) ArchiveExercise(ctx context.Context, id string) (*models.ArchiveResult, error) {
	return r.Resolver.ArchiveExercise(ctx, id)
}

// RestoreExercise is the resolver for the restoreExercise field.
func (r *mutationResolver) RestoreExercise(ctx context.Context, id string) (*models.ArchiveResult, error) {
	return r.Resolver.RestoreExercise(ctx, id)
}

// CreateCardioEntry is the resolver for the createCardioEntry field.
func (r *mutationResolver) CreateCardioEntry(ctx context.Context, input models.CreateCardioInput) (*models.CardioEntryResult, error) {
	return r.Resolver.CreateCardioEntry(ctx, input)
}

// UpdateCardioEntry is the resolver for the updateCardioEntry field.
func (r *mutationResolver) UpdateCardioEntry(ctx context.Context, id string, input models.UpdateCardioInput) (*models.CardioEntryResult, error) {
	return r.Resolver.UpdateCardioEntry(ctx, id, input)
}

// DeleteCardioEntry is the resolver for the deleteCardioEntry field.
func (r *mutationResolver) DeleteCardioEntry(ctx context.Context, id string) (*models.CardioEntryResult, error) {
	return r.Resolver.DeleteCardioEntry(ctx, id)
}

// CreateBodyWeightEntry is the resolver for the createBodyWeightEntry field.
func (r *mutationResolver) CreateBodyWeightEntry(ctx context.Context, input models.CreateBodyWeightInput) (*models.BodyWeightResult, error) {
	return r.Resolver.CreateBodyWeightEntry(ctx, input)
}

// UpdateBodyWeightEntry is the resolver for the updateBodyWeightEntry field.
func (r *mutationResolver) UpdateBodyWeightEntry(ctx context.Context, id string, input models.UpdateBodyWeightInput) (*models.BodyWeightResult, error) {
	return r.Resolver.UpdateBodyWeightEntry(ctx, id, input)
}

// DeleteBodyWeightEntry is the resolver for the deleteBodyWeightEntry field.
func (r *mutationResolver) DeleteBodyWeightEntry(ctx context.Context, id string) (*models.BodyWeightResult, error) {
	return r.Resolver.DeleteBodyWeightEntry(ctx, id)
}

// CreateBodyCheckIn is the resolver for the createBodyCheckIn field.
func (r *mutationResolver) CreateBodyCheckIn(ctx context.Context, input models.CreateCheckInInput) (*models.BodyCheckInResult, error) {
	return r.Resolver.CreateBodyCheckIn(ctx, input)
}

// UpdateBodyCheckIn is the resolver for the updateBodyCheckIn field.
func (r *mutationResolver) UpdateBodyCheckIn(ctx context.Context, id string, input models.UpdateCheckInInput) (*models.BodyCheckInResult, error) {
	return r.Resolver.UpdateBodyCheckIn(ctx, id, input)
}

// DeleteBodyCheckIn is the resolver for the deleteBodyCheckIn field.
func (r *mutationResolver) DeleteBodyCheckIn(ctx context.Context, id string) (*models.BodyCheckInResult, error) {
	return r.Resolver.DeleteBodyCheckIn(ctx, id)
}

// CreateBodyMeasurement is the resolver for the createBodyMeasurement field.
func (r *mutationResolver) CreateBodyMeasurement(ctx context.Context, checkInID string, input models.CreateMeasurementInput) (*models.BodyMeasurementResult, error) {
	return r.Resolver.CreateBodyMeasurement(ctx, checkInID, input)
}

// UpdateBodyMeasurement is the resolver for the updateBodyMeasurement field.
func (r *mutationResolver) UpdateBodyMeasurement(ctx context.Context, id string, input models.UpdateMeasurementInput) (*models.BodyMeasurementResult, error) {
	return r.Resolver.UpdateBodyMeasurement(ctx, id, input)
}

// DeleteBodyMeasurement is the resolver for the deleteBodyMeasurement field.
func (r *mutationResolver) DeleteBodyMeasurement(ctx context.Context, id string) (*models.BodyMeasurementResult, error) {
	return r.Resolver.DeleteBodyMeasurement(ctx, id)
}

// CreateWeekFlag is the resolver for the createWeekFlag field.
func (r *mutationResolver) CreateWeekFlag(ctx context.Context, input models.CreateWeekFlagInput) (*models.WeekFlagResult, error) {
	return r.Resolver.CreateWeekFlag(ctx, input)
}

// DeleteWeekFlag is the resolver for the deleteWeekFlag field.
func (r *mutationResolver) DeleteWeekFlag(ctx context.Context, id string) (*models.WeekFlagResult, error) {
	return r.Resolver.DeleteWeekFlag(ctx, id)
}

// CreateNutritionProduct is the resolver for the createNutritionProduct field.
func (r *mutationResolver) CreateNutritionProduct(ctx context.Context, input models.CreateProductInput) (*models.NutritionProductResult, error) {
	panic(fmt.Errorf("not implemented: CreateNutritionProduct - createNutritionProduct"))
}

// UpdateNutritionProduct is the resolver for the updateNutritionProduct field.
func (r *mutationResolver) UpdateNutritionProduct(ctx context.Context, id string, input models.UpdateProductInput) (*models.NutritionProductResult, error) {
	panic(fmt.Errorf("not implemented: UpdateNutritionProduct - updateNutritionProduct"))
}

// DeleteNutritionProduct is the resolver for the deleteNutritionProduct field.
func (r *mutationResolver) DeleteNutritionProduct(ctx context.Context, id string) (*models.NutritionProductResult, error) {
	panic(fmt.Errorf("not implemented: DeleteNutritionProduct - deleteNutritionProduct"))
}

// CreateNutritionTemplate is the resolver for the createNutritionTemplate field.
func (r *mutationResolver) CreateNutritionTemplate(ctx context.Context, input models.CreateTemplateInput) (*models.NutritionTemplateResult, error) {
	panic(fmt.Errorf("not implemented: CreateNutritionTemplate - createNutritionTemplate"))
}

// UpdateNutritionTemplate is the resolver for the updateNutritionTemplate field.
func (r *mutationResolver) UpdateNutritionTemplate(ctx context.Context, id string, input models.UpdateTemplateInput) (*models.NutritionTemplateResult, error) {
	panic(fmt.Errorf("not implemented: UpdateNutritionTemplate - updateNutritionTemplate"))
}

// DeleteNutritionTemplate is the resolver for the deleteNutritionTemplate field.
func (r *mutationResolver) DeleteNutritionTemplate(ctx context.Context, id string) (*models.NutritionTemplateResult, error) {
	panic(fmt.Errorf("not implemented: DeleteNutritionTemplate - deleteNutritionTemplate"))
}

// CreateNutritionTemplateItem is the resolver for the createNutritionTemplateItem field.
func (r *mutationResolver) CreateNutritionTemplateItem(ctx context.Context, input models.CreateTemplateItemInput) (*models.NutritionTemplateItemResult, error) {
	panic(fmt.Errorf("not implemented: CreateNutritionTemplateItem - createNutritionTemplateItem"))
}

// UpdateNutritionTemplateItem is the resolver for the updateNutritionTemplateItem field.
func (r *mutationResolver) UpdateNutritionTemplateItem(ctx context.Context, id string, input models.UpdateTemplateItemInput) (*models.NutritionTemplateItemResult, error) {
	panic(fmt.Errorf("not implemented: UpdateNutritionTemplateItem - updateNutritionTemplateItem"))
}

// DeleteNutritionTemplateItem is the resolver for the deleteNutritionTemplateItem field.
func (r *mutationResolver) DeleteNutritionTemplateItem(ctx context.Context, id string) (*models.NutritionTemplateItemResult, error) {
	panic(fmt.Errorf("not implemented: DeleteNutritionTemplateItem - deleteNutritionTemplateItem"))
}

// CreateDailyNutritionOverride is the resolver for the createDailyNutritionOverride field.
func (r *mutationResolver) CreateDailyNutritionOverride(ctx context.Context, input models.CreateOverrideInput) (*models.DailyNutritionOverrideResult, error) {
	panic(fmt.Errorf("not implemented: CreateDailyNutritionOverride - createDailyNutritionOverride"))
}

// UpdateDailyNutritionOverride is the resolver for the updateDailyNutritionOverride field.
func (r *mutationResolver) UpdateDailyNutritionOverride(ctx context.Context, id string, input models.UpdateOverrideInput) (*models.DailyNutritionOverrideResult, error) {
	panic(fmt.Errorf("not implemented: UpdateDailyNutritionOverride - updateDailyNutritionOverride"))
}

// DeleteDailyNutritionOverride is the resolver for the deleteDailyNutritionOverride field.
func (r *mutationResolver) DeleteDailyNutritionOverride(ctx context.Context, id string) (*models.DailyNutritionOverrideResult, error) {
	panic(fmt.Errorf("not implemented: DeleteDailyNutritionOverride - deleteDailyNutritionOverride"))
}

// CreateDailyNutritionOverrideItem is the resolver for the createDailyNutritionOverrideItem field.
func (r *mutationResolver) CreateDailyNutritionOverrideItem(ctx context.Context, input models.CreateOverrideItemInput) (*models.DailyNutritionOverrideItemResult, error) {
	panic(fmt.Errorf("not implemented: CreateDailyNutritionOverrideItem - createDailyNutritionOverrideItem"))
}

// UpdateDailyNutritionOverrideItem is the resolver for the updateDailyNutritionOverrideItem field.
func (r *mutationResolver) UpdateDailyNutritionOverrideItem(ctx context.Context, id string, input models.UpdateOverrideItemInput) (*models.DailyNutritionOverrideItemResult, error) {
	panic(fmt.Errorf("not implemented: UpdateDailyNutritionOverrideItem - updateDailyNutritionOverrideItem"))
}

// DeleteDailyNutritionOverrideItem is the resolver for the deleteDailyNutritionOverrideItem field.
func (r *mutationResolver) DeleteDailyNutritionOverrideItem(ctx context.Context, id string) (*models.DailyNutritionOverrideItemResult, error) {
	panic(fmt.Errorf("not implemented: DeleteDailyNutritionOverrideItem - deleteDailyNutritionOverrideItem"))
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*models.SettingsResult, error) {
	panic(fmt.Errorf("not implemented: Settings - settings"))
}

// Exercises is the resolver for the exercises field.
func (r *queryResolver) Exercises(ctx context.Context, first *int, after *string, includeInactive *bool) (*models.ExerciseConnection, error) {
	return r.Resolver.Exercises(ctx, first, after, includeInactive)
}

// Exercise is the resolver for the exercise field.
func (r *queryResolver) Exercise(ctx context.Context, id string) (*models.ExerciseResult, error) {
	return r.Resolver.GetExercise(ctx, id)
}

// AllExercises is the resolver for the allExercises field.
func (r *queryResolver) AllExercises(ctx context.Context, includeInactive *bool) ([]*models.Exercise, error) {
	return r.Resolver.AllExercises(ctx, includeInactive)
}

// CardioEntry is the resolver for the cardioEntry field.
func (r *queryResolver) CardioEntry(ctx context.Context, id string) (*models.CardioEntryResult, error) {
	return r.Resolver.GetCardioEntry(ctx, id)
}

// CardioEntries is the resolver for the cardioEntries field.
func (r *queryResolver) CardioEntries(ctx context.Context, date models.Date) (*models.CardioEntriesResult, error) {
	return r.Resolver.GetCardioEntries(ctx, date)
}

// BodyWeightEntry is the resolver for the bodyWeightEntry field.
func (r *queryResolver) BodyWeightEntry(ctx context.Context, id string) (*models.BodyWeightResult, error) {
	return r.Resolver.GetBodyWeightEntry(ctx, id)
}

// BodyWeightEntries is the resolver for the bodyWeightEntries field.
func (r *queryResolver) BodyWeightEntries(ctx context.Context, from models.Date, to models.Date) (*models.BodyWeightEntriesResult, error) {
	return r.Resolver.GetBodyWeightEntries(ctx, from, to)
}

// LatestBodyWeight is the resolver for the latestBodyWeight field.
func (r *queryResolver) LatestBodyWeight(ctx context.Context) (*models.BodyWeightResult, error) {
	return r.Resolver.GetLatestBodyWeight(ctx)
}

// BodyCheckIn is the resolver for the bodyCheckIn field.
func (r *queryResolver) BodyCheckIn(ctx context.Context, id string) (*models.BodyCheckInResult, error) {
	return r.Resolver.GetBodyCheckIn(ctx, id)
}

// BodyCheckIns is the resolver for the bodyCheckIns field.
func (r *queryResolver) BodyCheckIns(ctx context.Context, from models.Date, to models.Date) (*models.BodyCheckInsResult, error) {
	return r.Resolver.GetBodyCheckIns(ctx, from, to)
}

// BodyMeasurements is the resolver for the bodyMeasurements field.
func (r *queryResolver) BodyMeasurements(ctx context.Context, checkInID string) ([]*models.BodyMeasurement, error) {
	return r.Resolver.GetBodyMeasurements(ctx, checkInID)
}

// ProgressPhotos is the resolver for the progressPhotos field.
func (r *queryResolver) ProgressPhotos(ctx context.Context, checkInID string) (*models.ProgressPhotosResult, error) {
	return r.Resolver.GetProgressPhotos(ctx, checkInID)
}

// WeekFlags is the resolver for the weekFlags field.
func (r *queryResolver) WeekFlags(ctx context.Context, weekStartDate models.Date) (*models.WeekFlagsResult, error) {
	return r.Resolver.GetWeekFlags(ctx, weekStartDate)
}

// NutritionProducts is the resolver for the nutritionProducts field.
func (r *queryResolver) NutritionProducts(ctx context.Context) (*models.NutritionProductsResult, error) {
	panic(fmt.Errorf("not implemented: NutritionProducts - nutritionProducts"))
}

// NutritionProduct is the resolver for the nutritionProduct field.
func (r *queryResolver) NutritionProduct(ctx context.Context, id string) (*models.NutritionProductResult, error) {
	panic(fmt.Errorf("not implemented: NutritionProduct - nutritionProduct"))
}

// NutritionTemplates is the resolver for the nutritionTemplates field.
func (r *queryResolver) NutritionTemplates(ctx context.Context, startDate models.Date, endDate models.Date) (*models.NutritionTemplatesResult, error) {
	panic(fmt.Errorf("not implemented: NutritionTemplates - nutritionTemplates"))
}

// NutritionTemplate is the resolver for the nutritionTemplate field.
func (r *queryResolver) NutritionTemplate(ctx context.Context, id string) (*models.NutritionTemplateResult, error) {
	panic(fmt.Errorf("not implemented: NutritionTemplate - nutritionTemplate"))
}

// NutritionTemplateCurrent is the resolver for the nutritionTemplateCurrent field.
func (r *queryResolver) NutritionTemplateCurrent(ctx context.Context, weekStartDate models.Date) (*models.NutritionTemplateResult, error) {
	panic(fmt.Errorf("not implemented: NutritionTemplateCurrent - nutritionTemplateCurrent"))
}

// DailyNutritionOverrides is the resolver for the dailyNutritionOverrides field.
func (r *queryResolver) DailyNutritionOverrides(ctx context.Context, startDate models.Date, endDate models.Date) (*models.DailyNutritionOverridesResult, error) {
	panic(fmt.Errorf("not implemented: DailyNutritionOverrides - dailyNutritionOverrides"))
}

// DailyNutritionOverride is the resolver for the dailyNutritionOverride field.
func (r *queryResolver) DailyNutritionOverride(ctx context.Context, id string) (*models.DailyNutritionOverrideResult, error) {
	panic(fmt.Errorf("not implemented: DailyNutritionOverride - dailyNutritionOverride"))
}

// DailyNutritionOverrideByDate is the resolver for the dailyNutritionOverrideByDate field.
func (r *queryResolver) DailyNutritionOverrideByDate(ctx context.Context, date models.Date) (*models.DailyNutritionOverrideResult, error) {
	panic(fmt.Errorf("not implemented: DailyNutritionOverrideByDate - dailyNutritionOverrideByDate"))
}

// NutritionMacros is the resolver for the nutritionMacros field.
func (r *queryResolver) NutritionMacros(ctx context.Context, weekStartDate models.Date, date *models.Date) (*models.NutritionMacrosResult, error) {
	panic(fmt.Errorf("not implemented: NutritionMacros - nutritionMacros"))
}

// BodyWeightTrend is the resolver for the bodyWeightTrend field.
func (r *queryResolver) BodyWeightTrend(ctx context.Context, from *models.Date, to *models.Date) (*models.BodyWeightTrendResult, error) {
	return r.Resolver.GetBodyWeightTrend(ctx, from, to)
}

// MeasurementTrend is the resolver for the measurementTrend field.
func (r *queryResolver) MeasurementTrend(ctx context.Context, measurementType models.MeasurementType, from *models.Date, to *models.Date) (*models.MeasurementTrendResult, error) {
	return r.Resolver.GetMeasurementTrend(ctx, measurementType, from, to)
}

// MeasurementOverlay is the resolver for the measurementOverlay field.
func (r *queryResolver) MeasurementOverlay(ctx context.Context, measurementTypes []models.MeasurementType, from *models.Date, to *models.Date) (*models.MeasurementOverlayResult, error) {
	return r.Resolver.GetMeasurementOverlay(ctx, measurementTypes, from, to)
}

// NutritionWeeklyAverages is the resolver for the nutritionWeeklyAverages field.
func (r *queryResolver) NutritionWeeklyAverages(ctx context.Context, from *models.Date, to *models.Date) (*models.NutritionWeeklyAveragesResult, error) {
	return r.Resolver.GetNutritionWeeklyAverages(ctx, from, to)
}

// ExerciseProgress is the resolver for the exerciseProgress field.
func (r *queryResolver) ExerciseProgress(ctx context.Context, exerciseID string, from *models.Date, to *models.Date) (*models.ExerciseProgressResult, error) {
	return r.Resolver.GetExerciseProgress(ctx, exerciseID, from, to)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *mutationResolver) DeleteProgressPhoto(ctx context.Context, id string) (*models.CardioEntryResult, error) {
	panic(fmt.Errorf("not implemented: DeleteProgressPhoto - deleteProgressPhoto"))
}
