package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *userProfileResolver) CreatedAt(ctx context.Context, obj *models.UserProfile) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.CreatedAt)
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userProfileResolver) UpdatedAt(ctx context.Context, obj *models.UserProfile) (*time.Time, error) {
	return atlasGraphQLTimePtr(obj.UpdatedAt)
}

// ValidationError is the resolver for the validationError field.
func (r *userProfileResultResolver) ValidationError(ctx context.Context, obj *models.UserProfileResult) (*models.UserProfileValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *userProfileResultResolver) NotFoundError(ctx context.Context, obj *models.UserProfileResult) (*models.UserProfileNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *userProfileResultResolver) AuthError(ctx context.Context, obj *models.UserProfileResult) (*models.UserProfileAuthErr, error) {
	return obj.AuthErr, nil
}

// UserProfile returns generated.UserProfileResolver implementation.
func (r *Resolver) UserProfile() generated.UserProfileResolver { return &userProfileResolver{r} }

// UserProfileResult returns generated.UserProfileResultResolver implementation.
func (r *Resolver) UserProfileResult() generated.UserProfileResultResolver {
	return &userProfileResultResolver{r}
}

type userProfileResolver struct{ *Resolver }
type userProfileResultResolver struct{ *Resolver }
