package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *weekFlagResolver) CreatedAt(ctx context.Context, obj *models.WeekFlag) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.CreatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *weekFlagResolver) UpdatedAt(ctx context.Context, obj *models.WeekFlag) (*time.Time, error) {
	t, err := time.Parse(time.RFC3339Nano, obj.UpdatedAt)
	if err != nil {
		return nil, nil
	}
	return &t, nil
}

// ValidationError is the resolver for the validationError field.
func (r *weekFlagResultResolver) ValidationError(ctx context.Context, obj *models.WeekFlagResult) (*models.WeekFlagValidationErr, error) {
	return obj.ValidationErr, nil
}

// NotFoundError is the resolver for the notFoundError field.
func (r *weekFlagResultResolver) NotFoundError(ctx context.Context, obj *models.WeekFlagResult) (*models.WeekFlagNotFoundErr, error) {
	return obj.NotFoundErr, nil
}

// AuthError is the resolver for the authError field.
func (r *weekFlagResultResolver) AuthError(ctx context.Context, obj *models.WeekFlagResult) (*models.WeekFlagAuthErr, error) {
	return obj.AuthErr, nil
}

// ValidationError is the resolver for the validationError field.
func (r *weekFlagsResultResolver) ValidationError(ctx context.Context, obj *models.WeekFlagsResult) (*models.WeekFlagValidationErr, error) {
	return obj.ValidationErr, nil
}

// AuthError is the resolver for the authError field.
func (r *weekFlagsResultResolver) AuthError(ctx context.Context, obj *models.WeekFlagsResult) (*models.WeekFlagAuthErr, error) {
	return obj.AuthErr, nil
}

// WeekFlag returns generated.WeekFlagResolver implementation.
func (r *Resolver) WeekFlag() generated.WeekFlagResolver { return &weekFlagResolver{r} }

// WeekFlagResult returns generated.WeekFlagResultResolver implementation.
func (r *Resolver) WeekFlagResult() generated.WeekFlagResultResolver {
	return &weekFlagResultResolver{r}
}

// WeekFlagsResult returns generated.WeekFlagsResultResolver implementation.
func (r *Resolver) WeekFlagsResult() generated.WeekFlagsResultResolver {
	return &weekFlagsResultResolver{r}
}

type weekFlagResolver struct{ *Resolver }
type weekFlagResultResolver struct{ *Resolver }
type weekFlagsResultResolver struct{ *Resolver }
