package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"monorepo-template/apps/api/internal/atlas/graph/generated"
	"monorepo-template/apps/api/internal/atlas/models"
	"time"
)

// CreatedAt is the resolver for the createdAt field.
func (r *dailyLogResolver) CreatedAt(ctx context.Context, obj *models.DailyLog) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *dailyLogResolver) UpdatedAt(ctx context.Context, obj *models.DailyLog) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// ValidationError is the resolver for the validationError field.
func (r *dailyLogResultResolver) ValidationError(ctx context.Context, obj *models.DailyLogResult) (*models.DailyLogValidationErr, error) {
	panic(fmt.Errorf("not implemented: ValidationError - validationError"))
}

// NotFoundError is the resolver for the notFoundError field.
func (r *dailyLogResultResolver) NotFoundError(ctx context.Context, obj *models.DailyLogResult) (*models.DailyLogNotFoundErr, error) {
	panic(fmt.Errorf("not implemented: NotFoundError - notFoundError"))
}

// ConflictError is the resolver for the conflictError field.
func (r *dailyLogResultResolver) ConflictError(ctx context.Context, obj *models.DailyLogResult) (*models.DailyLogConflictErr, error) {
	panic(fmt.Errorf("not implemented: ConflictError - conflictError"))
}

// AuthError is the resolver for the authError field.
func (r *dailyLogResultResolver) AuthError(ctx context.Context, obj *models.DailyLogResult) (*models.DailyLogAuthErr, error) {
	panic(fmt.Errorf("not implemented: AuthError - authError"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *dailyLogSummaryResolver) UpdatedAt(ctx context.Context, obj *models.DailyLogSummary) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UpdateDailyLogNotes is the resolver for the updateDailyLogNotes field.
func (r *mutationResolver) UpdateDailyLogNotes(ctx context.Context, date models.Date, expectedVersion int, notes *string) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: UpdateDailyLogNotes - updateDailyLogNotes"))
}

// AddWorkoutExercise is the resolver for the addWorkoutExercise field.
func (r *mutationResolver) AddWorkoutExercise(ctx context.Context, date models.Date, expectedVersion int, input models.AddWorkoutExerciseInput) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: AddWorkoutExercise - addWorkoutExercise"))
}

// UpdateWorkoutExercise is the resolver for the updateWorkoutExercise field.
func (r *mutationResolver) UpdateWorkoutExercise(ctx context.Context, id string, expectedVersion int, input models.UpdateWorkoutExerciseGraphQLInput) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: UpdateWorkoutExercise - updateWorkoutExercise"))
}

// RemoveWorkoutExercise is the resolver for the removeWorkoutExercise field.
func (r *mutationResolver) RemoveWorkoutExercise(ctx context.Context, id string, expectedVersion int) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: RemoveWorkoutExercise - removeWorkoutExercise"))
}

// ReorderWorkoutExercises is the resolver for the reorderWorkoutExercises field.
func (r *mutationResolver) ReorderWorkoutExercises(ctx context.Context, date models.Date, expectedVersion int, orderedIds []string) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: ReorderWorkoutExercises - reorderWorkoutExercises"))
}

// AddWorkoutSet is the resolver for the addWorkoutSet field.
func (r *mutationResolver) AddWorkoutSet(ctx context.Context, workoutExerciseID string, expectedVersion int, input models.AddWorkoutSetInput) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: AddWorkoutSet - addWorkoutSet"))
}

// UpdateWorkoutSet is the resolver for the updateWorkoutSet field.
func (r *mutationResolver) UpdateWorkoutSet(ctx context.Context, id string, expectedVersion int, input models.UpdateWorkoutSetGraphQLInput) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: UpdateWorkoutSet - updateWorkoutSet"))
}

// RemoveWorkoutSet is the resolver for the removeWorkoutSet field.
func (r *mutationResolver) RemoveWorkoutSet(ctx context.Context, id string, expectedVersion int) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: RemoveWorkoutSet - removeWorkoutSet"))
}

// ReorderWorkoutSets is the resolver for the reorderWorkoutSets field.
func (r *mutationResolver) ReorderWorkoutSets(ctx context.Context, workoutExerciseID string, expectedVersion int, orderedIds []string) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: ReorderWorkoutSets - reorderWorkoutSets"))
}

// DailyLog is the resolver for the dailyLog field.
func (r *queryResolver) DailyLog(ctx context.Context, date models.Date) (*models.DailyLogResult, error) {
	panic(fmt.Errorf("not implemented: DailyLog - dailyLog"))
}

// DailyLogs is the resolver for the dailyLogs field.
func (r *queryResolver) DailyLogs(ctx context.Context, from models.Date, to models.Date) ([]*models.DailyLogSummary, error) {
	panic(fmt.Errorf("not implemented: DailyLogs - dailyLogs"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *workoutExerciseResolver) CreatedAt(ctx context.Context, obj *models.WorkoutExercise) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *workoutExerciseResolver) UpdatedAt(ctx context.Context, obj *models.WorkoutExercise) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// CreatedAt is the resolver for the createdAt field.
func (r *workoutSetResolver) CreatedAt(ctx context.Context, obj *models.WorkoutSet) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *workoutSetResolver) UpdatedAt(ctx context.Context, obj *models.WorkoutSet) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// DailyLog returns generated.DailyLogResolver implementation.
func (r *Resolver) DailyLog() generated.DailyLogResolver { return &dailyLogResolver{r} }

// DailyLogResult returns generated.DailyLogResultResolver implementation.
func (r *Resolver) DailyLogResult() generated.DailyLogResultResolver {
	return &dailyLogResultResolver{r}
}

// DailyLogSummary returns generated.DailyLogSummaryResolver implementation.
func (r *Resolver) DailyLogSummary() generated.DailyLogSummaryResolver {
	return &dailyLogSummaryResolver{r}
}

// WorkoutExercise returns generated.WorkoutExerciseResolver implementation.
func (r *Resolver) WorkoutExercise() generated.WorkoutExerciseResolver {
	return &workoutExerciseResolver{r}
}

// WorkoutSet returns generated.WorkoutSetResolver implementation.
func (r *Resolver) WorkoutSet() generated.WorkoutSetResolver { return &workoutSetResolver{r} }

type dailyLogResolver struct{ *Resolver }
type dailyLogResultResolver struct{ *Resolver }
type dailyLogSummaryResolver struct{ *Resolver }
type workoutExerciseResolver struct{ *Resolver }
type workoutSetResolver struct{ *Resolver }
