package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"monorepo-template/apps/api/internal/graph/model"
	"monorepo-template/apps/api/internal/middleware"
	"monorepo-template/apps/api/internal/service"
)

// LoginAdmin is the resolver for the loginAdmin field.
func (r *mutationResolver) LoginAdmin(ctx context.Context, input model.LoginAdminInput) (model.LoginAdminResult, error) {
	result, err := r.AdminAuthService.Login(ctx, service.LoginAdminInput{Email: input.Email, Password: input.Password})
	if err != nil {
		if errors.Is(err, service.ErrAdminAuth) {
			return model.AuthError{Message: "invalid email or password"}, nil
		}
		if errors.Is(err, service.ErrAdminValidation) {
			return model.ValidationError{Field: "email", Message: "invalid login input"}, nil
		}
		return nil, err
	}
	middleware.SetAdminSessionCookieFromContext(ctx, result.SessionID)
	return model.LoginAdminSuccess{Admin: mapAdmin(result.Admin)}, nil
}

// LogoutAdmin is the resolver for the logoutAdmin field.
func (r *mutationResolver) LogoutAdmin(ctx context.Context) (model.LogoutAdminResult, error) {
	sessionID := middleware.AdminSessionIDFromContext(ctx)
	if err := r.AdminAuthService.Logout(ctx, sessionID); err != nil {
		return nil, err
	}
	middleware.ClearAdminSessionCookieFromContext(ctx)
	return model.LogoutAdminSuccess{Ok: true}, nil
}

// CreateAdmin is the resolver for the createAdmin field.
func (r *mutationResolver) CreateAdmin(ctx context.Context, input model.CreateAdminInput) (model.CreateAdminResult, error) {
	actor, err := requireAdmin(ctx)
	if err != nil {
		return model.AuthError{Message: "admin authentication required"}, nil
	}
	admin, err := r.AdminAuthService.CreateAdmin(ctx, actor, service.NewAdminInput{
		Email:    input.Email,
		Name:     input.Name,
		Password: input.Password,
	})
	if err != nil {
		if errors.Is(err, service.ErrAdminDuplicateEmail) {
			return model.ValidationError{Field: "email", Message: "already exists"}, nil
		}
		if errors.Is(err, service.ErrAdminValidation) {
			return model.ValidationError{Field: "password", Message: "invalid admin input"}, nil
		}
		return nil, err
	}
	return model.CreateAdminSuccess{Admin: mapAdmin(admin)}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.AdminUser, error) {
	principal, ok := middleware.GetAdminPrincipal(ctx)
	if !ok {
		return nil, nil
	}
	return mapAdmin(&service.Admin{
		ID:        principal.ID,
		Email:     principal.Email,
		Name:      principal.Name,
		Role:      principal.Role,
		IsActive:  true,
		CreatedAt: principal.CreatedAt,
		UpdatedAt: principal.UpdatedAt,
	}), nil
}
