package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"encoding/base64"
	"fmt"
	"monorepo-template/apps/api/internal/graph/model"
	"monorepo-template/apps/api/internal/service"
	"monorepo-template/libs/go/logger"

	"go.uber.org/zap"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (model.CreateUserResult, error) {
	const op = "mutationResolver.CreateUser"
	if _, err := requireAdmin(ctx); err != nil {
		return model.AuthError{Message: "admin authentication required"}, nil
	}
	log := logger.FromContext(ctx).With(zap.String("op", op))
	log.Debug("resolving createUser", zap.String("email", input.Email))
	u, err := r.UserService.Create(ctx, mapCreateUserInput(input))
	if err != nil {
		if service.IsDuplicateEmail(err) {
			return model.ValidationError{Field: "email", Message: "already exists"}, nil
		}
		return nil, fmt.Errorf("%s: %w", op, err)
	}
	return model.CreateUserSuccess{User: mapUser(u)}, nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input model.UpdateUserInput) (model.UpdateUserResult, error) {
	const op = "mutationResolver.UpdateUser"
	if _, err := requireAdmin(ctx); err != nil {
		return model.AuthError{Message: "admin authentication required"}, nil
	}
	log := logger.FromContext(ctx).With(zap.String("op", op))
	log.Debug("resolving updateUser", zap.String("user_id", id))
	u, err := r.UserService.Update(ctx, id, mapUpdateUserInput(input))
	if err != nil {
		if service.IsDuplicateEmail(err) {
			return model.ValidationError{Field: "email", Message: "already exists"}, nil
		}
		return nil, fmt.Errorf("%s: %w", op, err)
	}
	if u == nil {
		return model.NotFoundError{Message: "user not found", EntityType: "User", ID: id}, nil
	}
	return model.UpdateUserSuccess{User: mapUser(u)}, nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (model.DeleteUserResult, error) {
	const op = "mutationResolver.DeleteUser"
	if _, err := requireAdmin(ctx); err != nil {
		return model.AuthError{Message: "admin authentication required"}, nil
	}
	log := logger.FromContext(ctx).With(zap.String("op", op))
	log.Debug("resolving deleteUser", zap.String("user_id", id))
	before, err := r.UserService.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("%s: lookup: %w", op, err)
	}
	if before == nil {
		return model.DeleteUserSuccess{Ok: false}, nil
	}
	if err := r.UserService.Delete(ctx, id); err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}
	return model.DeleteUserSuccess{Ok: true}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	const op = "queryResolver.User"
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	log := logger.FromContext(ctx).With(zap.String("op", op))
	log.Debug("resolving user", zap.String("user_id", id))
	u, err := r.UserService.GetByID(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}
	if u == nil {
		return nil, nil
	}
	return mapUser(u), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, pagination *model.PaginationInput) (*model.UserConnection, error) {
	const op = "queryResolver.Users"
	if _, err := requireAdmin(ctx); err != nil {
		return nil, err
	}
	log := logger.FromContext(ctx).With(zap.String("op", op))

	var first *int
	var after *string
	if pagination != nil {
		first = pagination.First
		after = pagination.After
	}
	log.Debug("resolving users", zap.Any("first", first), zap.Any("after", after))

	users, total, err := r.UserService.List(ctx, first, after)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	edges := make([]*model.UserEdge, len(users))
	for i, u := range users {
		edges[i] = &model.UserEdge{
			Cursor: base64.StdEncoding.EncodeToString([]byte(u.CreatedAt)),
			Node:   mapUser(u),
		}
	}

	var startCursor, endCursor *string
	if len(edges) > 0 {
		startCursor = &edges[0].Cursor
		endCursor = &edges[len(edges)-1].Cursor
	}

	limit := 20
	if first != nil && *first > 0 {
		limit = *first
	}
	hasNext := len(users) == limit && total > limit

	return &model.UserConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNext,
			HasPreviousPage: after != nil,
			StartCursor:     startCursor,
			EndCursor:       endCursor,
		},
		TotalCount: total,
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func mapUser(u *service.User) *model.User {
	return &model.User{
		ID:        u.ID,
		Email:     u.Email,
		Name:      u.Name,
		CreatedAt: u.CreatedAt,
		UpdatedAt: u.UpdatedAt,
	}
}
func mapCreateUserInput(in model.CreateUserInput) service.CreateUserInput {
	return service.CreateUserInput{
		Email:    in.Email,
		Name:     in.Name,
		Password: in.Password,
	}
}
func mapUpdateUserInput(in model.UpdateUserInput) service.UpdateUserInput {
	return service.UpdateUserInput{
		Name:  in.Name,
		Email: in.Email,
	}
}
